### ISSUE TITLE
Conda instructions

### ISSUE THREAD

**Issue by andrzejnovak** [DL4Jets/DeepJetCore#33]
@jkiesele any chance you could add back the conda install instructions? I am running on clusters where I cannot mount eos. Also running as is `bash setup_djcenv.sh gpu` I cannot subsequently compile the `compiled` directory with the following error ` boost/python/numpy.hpp: No such file or directory`

This seems to be a new dependency since I tried it last.

**Comment by jkiesele** [comment]
Hi,
you encounter exactly the last point that made me switch to containers. The available numpy, boost etc versions are a bit outdated. If you can't mount eos you can either:
  * copy the container (it is just one file)
  * create your own container using the files locaten in the docker subdirectory.

The conda installation can not be supported anymore, one reason being the reason you mentioned.

**Comment by andrzejnovak** [comment]
@jkiesele  Could you add a bit more instruction on running/building the container?

**Comment by jkiesele** [comment]
Hi,

Documentation has been added. Please let me know how it goes.

Best,
Jan

On 20 Nov 2019, at 00:56, Andrzej Novak <notifications@github.com<mailto:notifications@github.com>> wrote:


@jkiesele<https://github.com/jkiesele> Could you add a bit more instruction on running/building the container?

**Comment by andrzejnovak** [comment]
@andrzejnovak Cool that helps a bit, so if I need to do any changes to DeepJetCore I should try to get the "base" container (like https://hub.docker.com/r/cernml4reco/djc_ubuntu_rootbase) and compile on top of it?

**Comment by jkiesele** [comment]
Hi,

Please start from this one:
https://hub.docker.com/repository/docker/cernml4reco/djcbase

Jan

On 20 Nov 2019, at 16:28, Andrzej Novak <notifications@github.com<mailto:notifications@github.com>> wrote:


@andrzejnovak<https://github.com/andrzejnovak> Cool that helps a bit, so if I need to do any changes to DeepJetCore I should try to get the "base" container (like https://hub.docker.com/r/cernml4reco/djc_ubuntu_rootbase) and compile on top of it?
