### ISSUE TITLE
Moving to python 3

### ISSUE THREAD

**Issue by andrzejnovak** [DL4Jets/DeepJetCore#34]
Are there plans to move to python3 given python2 end-of-life

**Comment by jkiesele** [comment]
Yes, beginning of next year

**Comment by jkiesele** [comment]
work in progress:
https://github.com/DL4Jets/DeepJetCore/commits/tf2py3

Please check (soon) if subpackages still work.

**Comment by jkiesele** [comment]
Migration to python 3 done. 
Please report any issues
https://github.com/DL4Jets/DeepJetCore/commit/21daf2639d8caf652d35c03be80c3e27f5f2f17c
