### ISSUE TITLE
Error messages when running version 2 example

### ISSUE THREAD

**Issue by hhe62** [DL4Jets/DeepJetCore#35]
For the record, when I ran the version 2 example, two error messages appeared.

### 1. When running training_example.py:

File "Train/training_example.py", line 45
    print('Since the training is done, use the predict.py script to predict the model output on you test sample, e.g.:
                                                                                                                     ^
SyntaxError: EOL while scanning string literal

(The issue disappeared after joining the indicated line and the next line together)
 
### 2. When running predict.py:

Traceback (most recent call last):
  File "/usr/share/DJC/DeepJetCore/bin/predict.py", line 7, in <module>
    import setGPU
  File "/usr/local/lib/python2.7/dist-packages/setGPU.py", line 4, in <module>
    stats = gpustat.GPUStatCollection.new_query()
  File "/usr/local/lib/python2.7/dist-packages/gpustat/core.py", line 281, in new_query
    N.nvmlInit()
  File "/usr/local/lib/python2.7/dist-packages/pynvml.py", line 754, in nvmlInit
    _nvmlCheckReturn(ret)
  File "/usr/local/lib/python2.7/dist-packages/pynvml.py", line 405, in _nvmlCheckReturn
    raise NVMLError(ret)
pynvml.NVMLError_DriverNotLoaded: Driver Not Loaded

(The issue disappeared after commenting out "import setGPU" in the file)

**Comment by andrzejnovak** [comment]
I found setGPU functionality to be platform dependent, some places it was needed, some places it threw an error.

**Comment by jkiesele** [comment]
HI all,

Will be fixed in next release.
The fix is simple, setGPU must be enclosed in a try import statement.

Best,
Jan

On 20 Nov 2019, at 15:50, Andrzej Novak <notifications@github.com<mailto:notifications@github.com>> wrote:


I found setGPU functionality to be platform dependent, some places it was needed, some places it threw an error.

**Comment by jkiesele** [comment]
Fixed now, will be part of next release
