### ISSUE TITLE
some indexerror from the generator

### ISSUE THREAD

**Issue by emilbols** [DL4Jets/DeepJetCore#38]
running on a small set of files (600000 jets), i get such an error, after training for a couple of epochs with no issues.

Traceback (most recent call last):
  File "DeepFlavour.py", line 57, in <module>
    verbose=1,checkperiod=1)
  File "/usr/share/DJC/DeepJetCore/training/training_base.py", line 452, in trainModel
    **trainargs)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow_core/python/keras/engine/training.py", line 1296, in fit_generator
    steps_name='steps_per_epoch')
  File "/usr/local/lib/python2.7/dist-packages/tensorflow_core/python/keras/engine/training_generator.py", line 257, in model_iteration
    batch_size = int(nest.flatten(batch_data)[0].shape[0])
IndexError: list index out of range

I guess the batch_data is empty? you recognize this? Sorry i can't give you much more information, debugging is a bit difficult since im running using the built in djc.

**Comment by jkiesele** [comment]
Hi Emil,
thanks for reporting this. Weird.
I don't have time to check myself right now, but you can always switch to a development version of DeepJetCore by sourcing 'docker_env.sh' from you cloned repository (don't forget to compile). This will switch the paths so you are able to check what could be going on, and adapt.
The files you should probably take a look at are trainDataGenerator.cc and training_base, where you find an epoch loop. Maybe something with indicating a new epoch?

**Comment by jkiesele** [comment]
Only patched in #39. Needs more substantial investigation, therefore keeping this open for now

**Comment by jkiesele** [comment]
Some parts have been changed quite a bit (see e.g. e68a9a36fc4eb12b0c38956dafc1f611eb8ae267). The patch has been removed for now, please report if the problem appears again.

**Comment by jkiesele** [comment]
Generator has been fixed, it was reading the first file twice.
https://github.com/DL4Jets/DeepJetCore/commit/a12114f67c5e28474e7ad93424dba3a1ec5bf39e
