### ISSUE TITLE
[ci] conda WF failing

### ISSUE THREAD

**Issue by andrzejnovak** [DL4Jets/DeepJetCore#59]
Evaluation **https://github.com/DL4Jets/DeepJetCore/runs/2923190710?check_suite_focus=true** failing with 
```
The versions of libVc.a (1.4.1) and Vc/version.h (1.4.2) are incompatible. Aborting.
```

It appears root/root-numpy is not compatible with the latest vector-classes. Package differences between the last good run and the failing one:

```bash
['google-auth', '1.31.0', 'pyhd3eb1b0_0']
['google-auth', '1.32.0', 'pyhd3eb1b0_0']
['pip', '21.1.2', 'pyhd8ed1ab_0', 'conda-forge']
['pip', '21.1.3', 'pyhd8ed1ab_0', 'conda-forge']
['urllib3', '1.26.5', 'pyhd8ed1ab_0', 'conda-forge']
['urllib3', '1.26.6', 'pyhd8ed1ab_0', 'conda-forge']
['vector-classes', '1.4.1', 'h4bd325d_1', 'conda-forge']
['vector-classes', '1.4.2', 'h4bd325d_0', 'conda-forge']
```

Pinning `vector-classes <=1.4.1` in the env.yml should fix this. @jkiesele 

I can submit a fix ~tomorrow

**Comment by jkiesele** [comment]
Thanks!
No hurry from my side.

On 28 Jun 2021, at 09:40, Andrzej Novak ***@***.******@***.***>> wrote:



Evaluation https://github.com/DL4Jets/DeepJetCore/runs/2923190710?check_suite_focus=true failing with

The versions of libVc.a (1.4.1) and Vc/version.h (1.4.2) are incompatible. Aborting.


It appears root/root-numpy is not compatible with the latest vector-classes. Package differences between the last good run and the failing one:

['google-auth', '1.31.0', 'pyhd3eb1b0_0']
['google-auth', '1.32.0', 'pyhd3eb1b0_0']
['pip', '21.1.2', 'pyhd8ed1ab_0', 'conda-forge']
['pip', '21.1.3', 'pyhd8ed1ab_0', 'conda-forge']
['urllib3', '1.26.5', 'pyhd8ed1ab_0', 'conda-forge']
['urllib3', '1.26.6', 'pyhd8ed1ab_0', 'conda-forge']
['vector-classes', '1.4.1', 'h4bd325d_1', 'conda-forge']
['vector-classes', '1.4.2', 'h4bd325d_0', 'conda-forge']

Pinning vector-classes <=1.4.1 in the env.yml should fix this. @jkiesele<https://github.com/jkiesele>

I can submit a fix ~tomorrow

**Comment by andrzejnovak** [comment]
I've pinged the upstream devs, the issue is due to static linking and should get resolved there. If this persists >2 weeks we can pin it here

**Comment by jkiesele** [comment]
Thanks for following up!

On 28 Jun 2021, at 14:58, Andrzej Novak ***@***.******@***.***>> wrote:



I've pinged the upstream devs, the issue is due to static linking and should get resolved there. If this persists >2 weeks we can pin it here
